version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: puppeteer
    versions:
    - 5.5.0
    - 6.0.0
    - 7.0.0
    - 7.0.1
    - 7.0.4
    - 7.1.0
    - 8.0.0
  - dependency-name: cheerio
    versions:
    - 1.0.0-rc.5
  - dependency-name: ejs
    versions:
    - 3.1.5
  - dependency-name: lodash
    versions:
    - 4.17.20
